server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users,/api/users/**

            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders,/api/orders/**

            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/payments/**

            - id: notification-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/notifications/**



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: gateway,health,info