server:
  port: 8083

spring:
  cloud:
    openfeign:
      client:
        config:
          product-service:
            connectTimeout: 2000
            readTimeout: 3000

          payment-service:
            connectTimeout: 2000
            readTimeout: 3000

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    properties:
      spring.json.add.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: vamsi
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans


product-service:
  url: http://localhost:8082


payment-service:
  url: http://localhost:8084


resilience4j:
  circuitbreaker:
    instances:

      productService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      paymentService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:

      productService:
        maxAttempts: 3
        waitDuration: 1s

      paymentService:
        maxAttempts: 3
        waitDuration: 1s


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
