server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: vamsi
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG